### ISSUE TITLE
4WAY_HANDSHAKE_TIMEOUT ?

### ISSUE THREAD

**Issue by Sarah-C** [01Space/ESP32-C3-0.42LCD#1]
Arduino 1.8.15
Chip is ESP32-C3 (revision 3) 0.42 OLED
Espressif systems: https://github.com/espressif/arduino-esp32 (Version 2.0.4, also reverted to 2.0.3)

Running: WiFiWebClient.ino

The device isn't connecting to either of my two WiFi spots. I've tried it with my two little purple pcb units with the same result:
Both ESP32-C3 2.0.3 (as instructed on this github) and the current 2.0.4 both failed with the following:

```
Attempting to connect to SSID: Thelma
[  4623][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 0 - WIFI_READY
[  4659][V][WiFiGeneric.cpp:338] _arduino_event_cb(): STA Started
[  4659][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 2 - STA_START
[  4668][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
.......[  8929][V][WiFiGeneric.cpp:360] _arduino_event_cb(): STA Disconnected: SSID: Thelma, BSSID: b0:7f:b9:85:9a:d7, Reason: 15
[  8930][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
[  8936][W][WiFiGeneric.cpp:950] _eventCallback(): Reason: 15 - 4WAY_HANDSHAKE_TIMEOUT
```

I googled a bit, and seen this issue crop up in the past on older chips - it seems to be something that's "returned" on the C3.
One site suggested:
```

     esptool --port COM21 erase_flash

C:\Users\sarah\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\3.3.0>esptool --port COM21 erase_flash
esptool.py v3.3
Serial port COM21
Connecting...
Detecting chip type... ESP32-C3
Chip is ESP32-C3 (revision 3)
Features: Wi-Fi
Crystal is 40MHz
MAC: 84:f7:03:67:e0:60
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 18.7s
Hard resetting via RTS pin...
```
It flashed, but it didn't work.

I've also walked up to the access point with the device - in case the signal strength was bad...  no change.

**Comment by 01Space** [comment]
// Enter your WiFi SSID and password
char ssid[] = "xxxxxx";             // your network SSID (name)
char pass[] = "xxxxxxxxx";    // your network password (use for WPA, or use as key for WEP)

You need to change your network SSID and password here
